version: '2.1'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: playing_dom
        entrypoint: sh /home/start.sh
        volumes:
            - './web:/home/app'
        networks:
            static-network:
                ipv4_address: 172.81.1.2
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_playing_dom
        entrypoint: sh /app/start.sh
        volumes:
            - './nginx/conf/nginx.conf:/etc/nginx/nginx.conf'
            - './nginx/log:/var/log/nginx'
        networks:
            static-network:
                ipv4_address: 172.81.1.3
        ports:
            - '8888:80'
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.81.1.0/29
